import "./globals.css";
import { Montserrat } from 'next/font/google';
import Link from "next/link";

// font
const monteserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ['latin'],
variable: "--font-monteserrat"
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* navbar */}
        {/* the font name form the veriable on top */}
        <nav className={`flex justify-around items-end border-b border-yellow-600 pt-4 pb-2 text-white ${monteserrat.className}`}>
          <Link href="/" className="text-4xl font-bold">Movie Pass</Link>
          <ul className="flex gap-x-4 text-xl">
            <li>
              {/* the font name from tailwind config fiel */}
              <a href="/" className="font-monteserrat">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/contact">Contact</a>
            </li>
          </ul>
        </nav>

        {/* app content */}
        <section>{children}</section>
      </body>
    </html>
  );
}
